### ISSUE TITLE
Dates not initialised correctly

### ISSUE THREAD

**Issue by josephroffey** [offirgolan/ember-time-machine#25] opened 2016-06-28 14:56 UTC
We are using a time machine proxy around a model with a date attribute, and no matter what we set the date to, the proxy's property shows today's date.

We can access the correct date using model.dateField.content, but previous references to model.dateField always show the current date.

**Comment by offirgolan** [comment] 2016-06-28 17:25
@josephroffey this seems to be a bug. Im gonna go ahead and close this issue as its a duplicate of #24

**Closed by offirgolan** 2016-06-28 17:25 UTC

**Comment by offirgolan** [comment] 2016-06-28 18:51
@josephroffey fixed with `v0.0.2`! Thanks for bringing this to my attention 😺
